# Generated by Django 5.1.4 on 2025-01-06 13:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('financas', '0002_alter_totaldespesasfixas_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='despesafixa',
            name='paga',
            field=models.BooleanField(default=False),
        ),
    ]
