# Generated by Django 5.1.4 on 2025-01-06 13:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('financas', '0003_despesafixa_paga'),
    ]

    operations = [
        migrations.AddField(
            model_name='despesavariavel',
            name='paga',
            field=models.BooleanField(default=False),
        ),
    ]
