# Generated by Django 5.1.4 on 2025-01-06 22:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('financas', '0004_despesavariavel_paga'),
    ]

    operations = [
        migrations.AddField(
            model_name='cartaocredito',
            name='valor_total',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
    ]
